@echo off

set COPYCMD=/Y

copy source-Bottom.png Beach-Coast\Beach-Coast-Ocean-Bottom.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Ocean-BottomLeft.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Ocean-BottomRight.png
copy source-Top.png Beach-Coast\Beach-Coast-Ocean-Top.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Ocean-TopLeft.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Ocean-TopRight.png
copy source-Bottom.png Water-Ocean\Water-Ocean-Coast-Bottom.png
copy source-BottomLeft.png Water-Ocean\Water-Ocean-Coast-BottomLeft.png
copy source-BottomRight.png Water-Ocean\Water-Ocean-Coast-BottomRight.png
copy source-Top.png Water-Ocean\Water-Ocean-Coast-Top.png
copy source-TopLeft.png Water-Ocean\Water-Ocean-Coast-TopLeft.png
copy source-TopRight.png Water-Ocean\Water-Ocean-Coast-TopRight.png
copy source-Bottom.png Beach-Coast\Beach-Coast-Desert-Bottom.png
copy source-Bottom.png Beach-Coast\Beach-Coast-Grassland-Bottom.png
copy source-Bottom.png Beach-Coast\Beach-Coast-Mountain-Bottom.png
copy source-Bottom.png Beach-Coast\Beach-Coast-Plains-Bottom.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Desert-Bottom.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Grassland-Bottom.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Mountain-Bottom.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Plains-Bottom.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Desert-BottomLeft.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Grassland-BottomLeft.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Mountain-BottomLeft.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Plains-BottomLeft.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Desert-BottomLeft.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Grassland-BottomLeft.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Mountain-BottomLeft.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Plains-BottomLeft.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Desert-BottomRight.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Grassland-BottomRight.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Mountain-BottomRight.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Plains-BottomRight.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Desert-BottomRight.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Grassland-BottomRight.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Mountain-BottomRight.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Plains-BottomRight.png
copy source-Top.png Beach-Coast\Beach-Coast-Desert-Top.png
copy source-Top.png Beach-Coast\Beach-Coast-Grassland-Top.png
copy source-Top.png Beach-Coast\Beach-Coast-Mountain-Top.png
copy source-Top.png Beach-Coast\Beach-Coast-Plains-Top.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Desert-Top.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Grassland-Top.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Mountain-Top.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Plains-Top.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Desert-TopLeft.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Grassland-TopLeft.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Mountain-TopLeft.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Plains-TopLeft.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Desert-TopLeft.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Grassland-TopLeft.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Mountain-TopLeft.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Plains-TopLeft.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Desert-TopRight.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Grassland-TopRight.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Mountain-TopRight.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Plains-TopRight.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Desert-TopRight.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Grassland-TopRight.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Mountain-TopRight.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Plains-TopRight.png
copy source-Bottom.png Beach-Desert\Beach-Desert-Coast-Bottom.png
copy source-BottomLeft.png Beach-Desert\Beach-Desert-Coast-BottomLeft.png
copy source-BottomRight.png Beach-Desert\Beach-Desert-Coast-BottomRight.png
copy source-Top.png Beach-Desert\Beach-Desert-Coast-Top.png
copy source-TopLeft.png Beach-Desert\Beach-Desert-Coast-TopLeft.png
copy source-TopRight.png Beach-Desert\Beach-Desert-Coast-TopRight.png
copy source-Bottom.png Beach-Mountain\Beach-Mountain-Coast-Bottom.png
copy source-BottomLeft.png Beach-Mountain\Beach-Mountain-Coast-BottomLeft.png
copy source-BottomRight.png Beach-Mountain\Beach-Mountain-Coast-BottomRight.png
copy source-Top.png Beach-Mountain\Beach-Mountain-Coast-Top.png
copy source-TopLeft.png Beach-Mountain\Beach-Mountain-Coast-TopLeft.png
copy source-TopRight.png Beach-Mountain\Beach-Mountain-Coast-TopRight.png
copy source-Bottom.png Beach-Plains\Beach-Plains-Coast-Bottom.png
copy source-BottomLeft.png Beach-Plains\Beach-Plains-Coast-BottomLeft.png
copy source-BottomRight.png Beach-Plains\Beach-Plains-Coast-BottomRight.png
copy source-Top.png Beach-Plains\Beach-Plains-Coast-Top.png
copy source-TopLeft.png Beach-Plains\Beach-Plains-Coast-TopLeft.png
copy source-TopRight.png Beach-Plains\Beach-Plains-Coast-TopRight.png
copy source-Bottom.png Fresh-Desert\Fresh-Desert-Lakes-Bottom.png
copy source-BottomLeft.png Fresh-Desert\Fresh-Desert-Lakes-BottomLeft.png
copy source-BottomRight.png Fresh-Desert\Fresh-Desert-Lakes-BottomRight.png
copy source-Top.png Fresh-Desert\Fresh-Desert-Lakes-Top.png
copy source-TopLeft.png Fresh-Desert\Fresh-Desert-Lakes-TopLeft.png
copy source-TopRight.png Fresh-Desert\Fresh-Desert-Lakes-TopRight.png
copy source-Bottom.png Fresh-Grassland\Fresh-Grassland-Lakes-Bottom.png
copy source-BottomLeft.png Fresh-Grassland\Fresh-Grassland-Lakes-BottomLeft.png
copy source-BottomRight.png Fresh-Grassland\Fresh-Grassland-Lakes-BottomRight.png
copy source-Top.png Fresh-Grassland\Fresh-Grassland-Lakes-Top.png
copy source-TopLeft.png Fresh-Grassland\Fresh-Grassland-Lakes-TopLeft.png
copy source-TopRight.png Fresh-Grassland\Fresh-Grassland-Lakes-TopRight.png
copy source-Bottom.png Fresh-Mountain\Fresh-Mountain-Lakes-Bottom.png
copy source-BottomLeft.png Fresh-Mountain\Fresh-Mountain-Lakes-BottomLeft.png
copy source-BottomRight.png Fresh-Mountain\Fresh-Mountain-Lakes-BottomRight.png
copy source-Top.png Fresh-Mountain\Fresh-Mountain-Lakes-Top.png
copy source-TopLeft.png Fresh-Mountain\Fresh-Mountain-Lakes-TopLeft.png
copy source-TopRight.png Fresh-Mountain\Fresh-Mountain-Lakes-TopRight.png
copy source-Bottom.png Fresh-Plains\Fresh-Plains-Lakes-Bottom.png
copy source-BottomLeft.png Fresh-Plains\Fresh-Plains-Lakes-BottomLeft.png
copy source-BottomRight.png Fresh-Plains\Fresh-Plains-Lakes-BottomRight.png
copy source-Top.png Fresh-Plains\Fresh-Plains-Lakes-Top.png
copy source-TopLeft.png Fresh-Plains\Fresh-Plains-Lakes-TopLeft.png
copy source-TopRight.png Fresh-Plains\Fresh-Plains-Lakes-TopRight.png
copy source-Bottom.png Beach-Grassland\Beach-Grassland-Coast-Bottom.png
copy source-BottomLeft.png Beach-Grassland\Beach-Grassland-Coast-BottomLeft.png
copy source-BottomRight.png Beach-Grassland\Beach-Grassland-Coast-BottomRight.png
copy source-Top.png Beach-Grassland\Beach-Grassland-Coast-Top.png
copy source-TopLeft.png Beach-Grassland\Beach-Grassland-Coast-TopLeft.png
copy source-TopRight.png Beach-Grassland\Beach-Grassland-Coast-TopRight.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Snow-Bottom.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Tundra-Bottom.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Snow-BottomLeft.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Tundra-BottomLeft.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Snow-BottomRight.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Tundra-BottomRight.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Snow-Top.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Tundra-Top.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Snow-TopLeft.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Tundra-TopLeft.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Snow-TopRight.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Tundra-TopRight.png
