@echo off

:: Specific to Ultima V edges
:: Changes to sprite edges should be made to source-*.png's

set COPYCMD=/Y

copy source-Bottom.png Beach-Coast\Beach-Coast-Desert-Bottom.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Desert-BottomLeft.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Desert-BottomRight.png
copy source-Top.png Beach-Coast\Beach-Coast-Desert-Top.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Desert-TopLeft.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Desert-TopRight.png
copy source-Bottom.png Beach-Coast\Beach-Coast-Grassland-Bottom.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Grassland-BottomLeft.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Grassland-BottomRight.png
copy source-Top.png Beach-Coast\Beach-Coast-Grassland-Top.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Grassland-TopLeft.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Grassland-TopRight.png
copy source-Bottom.png Beach-Coast\Beach-Coast-Mountain-Bottom.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Mountain-BottomLeft.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Mountain-BottomRight.png
copy source-Top.png Beach-Coast\Beach-Coast-Mountain-Top.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Mountain-TopLeft.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Mountain-TopRight.png
copy source-Bottom.png Beach-Coast\Beach-Coast-Plains-Bottom.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Plains-BottomLeft.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Plains-BottomRight.png
copy source-Top.png Beach-Coast\Beach-Coast-Plains-Top.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Plains-TopLeft.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Plains-TopRight.png
copy source-Bottom.png Beach-Coast\Beach-Coast-Desert-Bottom.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Desert-BottomLeft.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Desert-BottomRight.png
copy source-Top.png Beach-Coast\Beach-Coast-Desert-Top.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Desert-TopLeft.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Desert-TopRight.png
copy source-Bottom.png Beach-Coast\Beach-Coast-Grassland-Bottom.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Grassland-BottomLeft.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Grassland-BottomRight.png
copy source-Top.png Beach-Coast\Beach-Coast-Grassland-Top.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Grassland-TopLeft.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Grassland-TopRight.png
copy source-Bottom.png Beach-Coast\Beach-Coast-Mountain-Bottom.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Mountain-BottomLeft.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Mountain-BottomRight.png
copy source-Top.png Beach-Coast\Beach-Coast-Mountain-Top.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Mountain-TopLeft.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Mountain-TopRight.png
copy source-Bottom.png Beach-Coast\Beach-Coast-Plains-Bottom.png
copy source-BottomLeft.png Beach-Coast\Beach-Coast-Plains-BottomLeft.png
copy source-BottomRight.png Beach-Coast\Beach-Coast-Plains-BottomRight.png
copy source-Top.png Beach-Coast\Beach-Coast-Plains-Top.png
copy source-TopLeft.png Beach-Coast\Beach-Coast-Plains-TopLeft.png
copy source-TopRight.png Beach-Coast\Beach-Coast-Plains-TopRight.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Desert-Bottom.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Desert-BottomLeft.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Desert-BottomRight.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Desert-Top.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Desert-TopLeft.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Desert-TopRight.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Grassland-Bottom.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Grassland-BottomLeft.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Grassland-BottomRight.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Grassland-Top.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Grassland-TopLeft.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Grassland-TopRight.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Mountain-Bottom.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Mountain-BottomLeft.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Mountain-BottomRight.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Mountain-Top.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Mountain-TopLeft.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Mountain-TopRight.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Plains-Bottom.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Plains-BottomLeft.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Plains-BottomRight.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Plains-Top.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Plains-TopLeft.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Plains-TopRight.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Snow-Bottom.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Snow-BottomLeft.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Snow-BottomRight.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Snow-Top.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Snow-TopLeft.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Snow-TopRight.png
copy source-Bottom.png Fresh-Lakes\Fresh-Lakes-Tundra-Bottom.png
copy source-BottomLeft.png Fresh-Lakes\Fresh-Lakes-Tundra-BottomLeft.png
copy source-BottomRight.png Fresh-Lakes\Fresh-Lakes-Tundra-BottomRight.png
copy source-Top.png Fresh-Lakes\Fresh-Lakes-Tundra-Top.png
copy source-TopLeft.png Fresh-Lakes\Fresh-Lakes-Tundra-TopLeft.png
copy source-TopRight.png Fresh-Lakes\Fresh-Lakes-Tundra-TopRight.png
